### PR TITLE
Completly refactored

### PR DESCRIPTION
**Pull request by rubenhortas**

### CODE REVIEW

**Comment by rodrigorega** [comment]
I downloaded your pull, when I run it I get this:

```
python .\wordlist_compare.py -m ..\my_mails.txt -l ..\google_5000000.txt
[*] Starting...
[!] 'module' object has no attribute 'PROT_READ'
[*] Exiting
```

I am using Python 2.7.8.

**Comment by rubenhortas** [comment]
Sorry. It was my fault. prot=mmap.PROT_READ is Unix specific. I changed it for access=mmap.ACCESS_READ. Should work.

**Comment by rodrigorega** [comment]
Awesome, thanks!

**Comment by rubenhortas** [comment]
Yw! ;)

**Pull request merged**
